### ISSUE TITLE
Get allert more then one time

### ISSUE THREAD

**Issue by shirser121** [eladnava/pikud-haoref-api#15]
When the alert is on, the JSON file stays with it for a while, so we get the alert more than one time.
Should check the timestamp and filter the alert before the timestamp

**Comment by eladnava** [comment]
Hi @shirser121,
At the moment, `pikud-haoref-api` provides a wrapper around the Home Front Command's `alerts.json` API, taking care of things like strange encodings and BOMs.

To listen for rocket alerts, you must poll the API by repeatedly calling `pikudHaoref.getActiveRocketAlertCities()`, which will usually return an empty JSON array, until there is an active code red alert. 

Indeed, the same city names will be repeatedly returned by the HFC API during the code red alert, for a period of about 30 seconds.

Since the purpose of this package is to query the HFC API, it is currently not in its scope to filter the results of the API based on whether the alert was previously returned - I believe it best to let the application consuming this API to take care of that.

It is quite easy for the consuming application to create a dictionary of city names and their last alert timestamp, to check if the returned alerts from the HFC API have already been processed recently.

Please let me know if this makes sense and if you have any further questions.
