### ISSUE TITLE
An example of an alert

### ISSUE THREAD

**Issue by yakirdayan** [eladnava/pikud-haoref-api#19]
Can you provide us an example of how the notification is received on the pikud-haoref servers?

**Comment by eladnava** [comment]
Hi @yakirdayan,
Sure.

The Pikud Haoref API returns a JSON response with a `data` array, where each element of the array is a name of a city/zone defined in the [`citiesArchive.json`](https://github.com/eladnava/pikud-haoref-api/blob/master/citiesArchive.js).

```
{
      "data": [
             "תל אביב - דרום העיר ויפו",
             "חיפה - מערב"
       ]
}
```

However, when you call `pikudHaoref.getActiveRocketAlertCities()`, then your callback will receive an array directly called `alertCities` with the list of cities inside the `data` object:

```
    // Get currently active rocket alert cities as an array
    pikudHaoref.getActiveRocketAlertCities(function (err, alertCities) {
        // alertCities will contain an array of cities like so: ["תל אביב - מזרח", "חיפה - כרמל ועיר תחתית", "עין גדי"]
```

Most of the time, the array returned will be empty because there are no currently active "צבע אדום" alerts for any city.

**Comment by yakirdayan** [comment]
I still can't figure out how you read the data with the JSON file locked

**Comment by eladnava** [comment]
Hi @yakirdayan,
The Pikud Haoref API package takes care of reading the JSON file from Pikud Haoref, which is sometimes empty or returned in a strange encoding. 

Just import the package and use it, there is no need to deal with the JSON file directly.

**Comment by yakirdayan** [comment]
When I change the domain in the app

     public static String API_ENDPOINT = "https://redalert.me";

Unable to receive notifications
